export const mockFirstFilm = {
  title: 'A New Hope',
  episode_id: 4,
  opening_crawl:
    "It is a period of civil war.\r\nRebel spaceships, striking\r\nfrom a hidden base, have won\r\ntheir first victory against\r\nthe evil Galactic Empire.\r\n\r\nDuring the battle, Rebel\r\nspies managed to steal secret\r\nplans to the Empire's\r\nultimate weapon, the DEATH\r\nSTAR, an armored space\r\nstation with enough power\r\nto destroy an entire planet.\r\n\r\nPursued by the Empire's\r\nsinister agents, Princess\r\nLeia races home aboard her\r\nstarship, custodian of the\r\nstolen plans that can save her\r\npeople and restore\r\nfreedom to the galaxy....",
  director: 'George Lucas',
  producer: 'Gary Kurtz, Rick McCallum',
  release_date: '1977-05-25',
  characters: ['https://swapi.dev/api/people/1/'],
  planets: ['https://swapi.dev/api/planets/1/'],
  starships: [
    'https://swapi.dev/api/starships/2/',
    'https://swapi.dev/api/starships/3/',
  ],
  vehicles: ['https://swapi.dev/api/vehicles/4/'],
  species: [
    'https://swapi.dev/api/species/1/',
    'https://swapi.dev/api/species/2/',
  ],
  created: '2014-12-10T14:23:31.880000Z',
  edited: '2014-12-20T19:49:45.256000Z',
  url: 'https://swapi.dev/api/films/1/',
};

export const mockAxiosSpecies = [
  {
    name: 'Human',
    classification: 'mammal',
    designation: 'sentient',
    average_height: '180',
    skin_colors: 'caucasian, black, asian, hispanic',
    hair_colors: 'blonde, brown, black, red',
    eye_colors: 'brown, blue, green, hazel, grey, amber',
    average_lifespan: '120',
    homeworld: 'https://swapi.dev/api/planets/9/',
    language: 'Galactic Basic',
    people: ['https://swapi.dev/api/people/66/'],
    films: ['https://swapi.dev/api/films/1/'],
    created: '2014-12-10T13:52:11.567000Z',
    edited: '2014-12-20T21:36:42.136000Z',
    url: 'https://swapi.dev/api/species/1/',
  },
  {
    name: 'Droid',
    classification: 'artificial',
    designation: 'sentient',
    average_height: 'n/a',
    skin_colors: 'n/a',
    hair_colors: 'n/a',
    eye_colors: 'n/a',
    average_lifespan: 'indefinite',
    homeworld: null,
    language: 'n/a',
    people: ['https://swapi.dev/api/people/2/'],
    films: ['https://swapi.dev/api/films/1/'],
    created: '2014-12-10T15:16:16.259000Z',
    edited: '2014-12-20T21:36:42.139000Z',
    url: 'https://swapi.dev/api/species/2/',
  },
];
